import {StyleSheet, Text, TouchableOpacity, View} from 'react-native';
import React from 'react';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import Colors from '../../constants/Colors';
import {
  Menu,
  MenuOption,
  MenuOptions,
  MenuTrigger,
} from 'react-native-popup-menu';
import {StackNavigationProp} from '@react-navigation/stack';
import {RootStackParamList} from '../../navigation/Navigation';
import {useNavigation} from '@react-navigation/native';
import {FlatList} from 'react-native';

const PartsListing = (data: any) => {
  const recordData = data?.route?.params?.data;

  // console.log('Recorded Data = ', recordData);

  const carParts = [
    {
      id: 1,
      part_name: 'Engine Control Unit',
      part_number: 'ECU-12345',
      manufacturer: 'Bosch',
      price: 2500.0,
      stock_quantity: 0, // Out of stock
      description:
        "The Engine Control Unit (ECU) is a crucial component responsible for managing the engine's performance. This Bosch ECU ensures optimal engine functioning and efficiency.",
      image: require('../../assets/Images/PartsImages/ECU.jpeg'),
      hs_code: 85371090,
      inventory: 'Engine Inventory',
    },
    {
      id: 2,
      part_name: 'Alternator',
      part_number: 'ALT-98765',
      manufacturer: 'Denso',
      price: 25000.0,
      stock_quantity: 25,
      description:
        'The alternator plays a vital role in charging the battery and providing power to the electrical system. This Denso alternator is known for its reliability and consistent performance.',
      image: require('../../assets/Images/PartsImages/Alterntor.jpg'),
      hs_code: 85115000,
      inventory: 'Engine Inventory',
    },
    {
      id: 3,
      part_name: 'Brake Pad Set',
      part_number: 'BP-45678',
      manufacturer: 'Brembo',
      price: 1200.0,
      stock_quantity: 0, // Out of stock
      description:
        'The brake pad set by Brembo offers exceptional braking performance and durability. Designed to withstand high temperatures and provide consistent stopping power.',
      image: require('../../assets/Images/PartsImages/BrakePad.png'),
      hs_code: 87083090,
      inventory: 'Brake Parts Inventory',
    },
    {
      id: 4,
      part_name: 'Spark Plug',
      part_number: 'SP-11223',
      manufacturer: 'NGK',
      price: 550.0,
      stock_quantity: 150,
      description:
        'NGK Spark Plugs are engineered to deliver exceptional ignition performance in all conditions. Ensure smooth engine operation with these high-quality spark plugs.',
      image: require('../../assets/Images/PartsImages/Sparkplug.png'),
      hs_code: 85111000,
      inventory: 'Plugs Inventory',
    },
    {
      id: 5,
      part_name: 'Fuel Pump',
      part_number: 'FP-33445',
      manufacturer: 'Walbro',
      price: 8500.0,
      stock_quantity: 0, // Out of stock
      description:
        'The Walbro Fuel Pump delivers a consistent flow of fuel to the engine, ensuring optimal performance and fuel efficiency. Trusted by enthusiasts and professionals alike.',
      image: require('../../assets/Images/PartsImages/FuelPump.png'),
      hs_code: '8413.30.90',
      inventory: 'Fuel Inventory',
    },
    {
      id: 6,
      part_name: 'Oil Filter',
      part_number: 'OF-22334',
      manufacturer: 'Mann-Filter',
      price: 1000.0,
      stock_quantity: 80,
      description:
        'Mann-Filter Oil Filters provide superior filtration efficiency, protecting your engine from harmful contaminants. Maintain engine health and prolong its lifespan with these premium filters.',
      image: require('../../assets/Images/PartsImages/carFilter.png'),
      hs_code: 84212300,
      inventory: 'Radiator & Filter',
    },
    {
      id: 7,
      part_name: 'Air Filter',
      part_number: 'AF-66778',
      manufacturer: 'K&N',
      price: 2500.0,
      stock_quantity: 60,
      description:
        "K&N Air Filters are designed to increase horsepower and acceleration while providing excellent filtration. Enhance your engine's performance and protect it from harmful particles.",
      image: require('../../assets/Images/PartsImages/AirFilter.png'),
      hs_code: 84213100,
      inventory: 'Radiator & Filter',
    },
    {
      id: 8,
      part_name: 'Radiator',
      part_number: 'RAD-88990',
      manufacturer: 'Behr',
      price: 1500.0,
      stock_quantity: 0, // Out of stock
      description:
        'The Behr Radiator efficiently dissipates heat generated by the engine, ensuring optimal operating temperatures. Constructed with high-quality materials for durability and reliability.',
      image: require('../../assets/Images/PartsImages/Raditor.jpg'),
      hs_code: 87089100,
      inventory: 'Radiator & Filter',
    },
    {
      id: 9,
      part_name: 'Transmission Fluid',
      part_number: 'TF-33456',
      manufacturer: 'Valvoline',
      price: 12000.0,
      stock_quantity: 45,
      description:
        'Valvoline Transmission Fluid is formulated to provide smooth shifting and reliable performance in automatic transmissions. Protect your transmission with this high-quality fluid.',
      image: require('../../assets/Images/PartsImages/Transmision.png'),
      hs_code: 38190000,
      inventory: 'Fluids Inventory',
    },
    {
      id: 10,
      part_name: 'Timing Belt',
      part_number: 'TB-99887',
      manufacturer: 'Gates',
      price: 950.0,
      stock_quantity: 30,
      description:
        'The Gates Timing Belt ensures precise synchronization of engine components, preventing costly damage from timing belt failure. Trust Gates for reliable timing belt solutions.',
      image: require('../../assets/Images/PartsImages/timing.png'),
      hs_code: 87089990,
      inventory: 'Belt Inventory',
    },
  ];

  const navigation = useNavigation<StackNavigationProp<RootStackParamList>>();

  const handleMenuSelect = (value: any) => {
    switch (value) {
      case 'Vehicle Details':
        navigation.navigate('VehicleDetails');
        break;
      default:
        break;
    }
  };

  const renderItem = (event: any) => {
    return (
      <View
        style={{
          flexDirection: 'row',
        }}>
        <View
          style={{
            borderRadius: 10,
            elevation: 7,
            padding: 15,
            backgroundColor: Colors.Iconwhite,
            marginVertical: 8,
            flexDirection: 'row',
          }}>
          <View
            style={{
              flexDirection: 'row',
              justifyContent: 'space-between',
              width: '83%',
            }}>
            <Text
              style={{fontSize: 18, fontWeight: '400', color: Colors.black}}>
              {event?.item?.part_name}
            </Text>
            <View style={{flexDirection: 'row', justifyContent: 'flex-end'}}>
              <TouchableOpacity>
                <Icon name="pencil" size={20} color={Colors.primary} />
              </TouchableOpacity>
              <TouchableOpacity>
                <Icon name="delete" size={20} color={Colors.red} />
              </TouchableOpacity>
            </View>
          </View>
        </View>
        <View
          style={{
            width: '12%',
            borderRadius: 11,
            justifyContent: 'center',
            alignItems: 'center',
            elevation: 7,
            backgroundColor: Colors.Iconwhite,
            marginVertical: 8,
            marginLeft: 10,
          }}>
          <Text style={{fontSize: 18, fontWeight: 'bold', color: Colors.black}}>
            {event?.item?.stock_quantity}
          </Text>
        </View>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <View
        style={{
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}>
        <View style={{flexDirection: 'row', alignItems: 'center'}}>
          <Icon name="arrow-left" size={30} color={Colors.black} />
          <Text
            style={{
              fontSize: 18,
              fontWeight: 'bold',
              color: Colors.black,
              marginLeft: 5,
            }}>
            Add Parts
          </Text>
        </View>
        <View style={{flexDirection: 'row', alignItems: 'center'}}>
          <TouchableOpacity>
            <Icon
              name="plus-circle"
              size={30}
              color={Colors.primary}
              onPress={() => {
                navigation.navigate('PartsStockList');
              }}
            />
          </TouchableOpacity>
          <Menu>
            <MenuTrigger>
              <Icon name="dots-vertical" size={24} color={Colors.black} />
            </MenuTrigger>
            <MenuOptions>
              <MenuOption onSelect={() => handleMenuSelect('Vehicle Details')}>
                <Text style={styles.menuText}>Vehicle Details</Text>
              </MenuOption>
            </MenuOptions>
          </Menu>
        </View>
      </View>
      <View style={{marginHorizontal: 10, marginTop: 20}}>
        <Text style={{fontSize: 18, fontWeight: '400', color: Colors.black}}>
          #{recordData?.service_number}
        </Text>
        <Text style={{fontSize: 18, fontWeight: '400', color: Colors.black}}>
          {recordData?.vehicle}
        </Text>
        <FlatList
          data={carParts}
          renderItem={renderItem}
          showsVerticalScrollIndicator={false}
          keyExtractor={(item, index) => String(index)}
          initialNumToRender={5} // Adjust numbers based on your list size and performance
          maxToRenderPerBatch={5}
          windowSize={5}
          style={{marginTop:10}}
          ListEmptyComponent={
            <Text style={styles.noDataText}>No data found.</Text>
          }
        />
      </View>
    </View>
  );
};

export default PartsListing;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F3F3',
    marginHorizontal: 10,
    marginVertical: 10,
  },
  menuText: {
    padding: 10,
    fontSize: 16,
  },
  noDataText: {
    color: Colors.black,
    fontSize: 18,
    textAlign: 'center',
  },
});
